apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-vcluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sowmyav27/argocd-app-config.git'
    targetRevision: HEAD
    path: vcluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-vcluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
