apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sowmyav27/argocd-app-config.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
