apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.21.0-beta.6
    chart: vcluster
    helm:
      releaseName: argocd
      values: |
        controlPlane:
          ingress:
            enabled: true
            host: demo.argocd.local
            spec:
              ingressClassName: nginx
          proxy:
            extraSANs:
            - demo.argocd.local
        sync:
          fromHost:
            ingressClasses:
              enabled: true
          toHost:
            ingresses:
              enabled: true
  sources: []
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
